[project]
name = "sharevault"
description = "Encrypted file sharing registry"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.sharevault]
path = "contracts/sharevault.clar"

[repl.analysis]
passes = ["check_checker"]
